version: "3.8"

# Usa questo stack nel Web editor di Portainer per eseguire direttamente l'app
# clonando la repo via comandi shell all'avvio del container. Nessun registry richiesto.

services:
  omg-youtube:
    image: node:20-bookworm-slim
    container_name: omg-youtube
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3100
      # Imposta a dominio:porta pubblico se esponi dietro reverse proxy (solo per mostrare URL nella UI)
      - PUBLIC_HOST=localhost:3100
    ports:
      - "3100:3100"
    volumes:
      # Persiste solo i dati di configurazione dell'addon
      - omg-youtube-data:/srv/app/data
    working_dir: /srv
    command: >-
      bash -lc '
        set -euo pipefail && \
        apt-get update && \
        apt-get install -y --no-install-recommends git ffmpeg yt-dlp ca-certificates && \
        rm -rf /var/lib/apt/lists/* && \
        mkdir -p /srv && cd /srv && \
        if [ ! -d app/.git ]; then \
          git clone --depth 1 https://github.com/mccoy88f/OMG-YouTube.git app; \
        else \
          cd app && git pull --ff-only && cd ..; \
        fi && \
        cd app && npm install --omit=dev && node src/index.js'

volumes:
  omg-youtube-data:


